version: '3.7'

services:
    currency-exchange:
        image: placidpj/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
        ports:
         - "8000:8000"
        networks:
         - currency-network 
        depends_on:
         - naming-server   
# hyphen(-) is used above because it is an array  
        environment:
          EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka      
    naming-server:
        image: placidpj/mmv2-naming-server:0.0.1-SNAPSHOT
        ports:
         - "8761:8761"
        networks:
         - currency-network 
networks:
   currency-network: